# Generated by Django 2.2.6 on 2019-10-18 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('storyline', models.TextField()),
                ('times_watched', models.IntegerField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie.Genre')),
            ],
        ),
    ]
